"""awal

Revision ID: a13f14d16b83
Revises: 
Create Date: 2026-09-21 03:25:45.300597

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a13f14d16b83'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    sa.Enum("pending_pair", "active", "needs_reconnect", "blocked", "unreachable",
            "disabled", name="site_status").create(op.get_bind())
    sa.Enum("core", "plugin", "theme", name="package_type").create(op.get_bind())
    sa.Enum("scan_site", "update_package", "verify_site", name="job_type").create(op.get_bind())
    sa.Enum("pending", "running", "success", "failed", "unknown", name="job_status").create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nama', sa.Text(), nullable=False),
    sa.Column('kontak', sa.Text(), nullable=True),
    sa.Column('catatan', sa.Text(), nullable=True),
    sa.Column('dibuat_pada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('nama', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('dibuat_pada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('nama', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status', postgresql.ENUM('pending_pair', 'active', 'needs_reconnect', 'blocked', 'unreachable', 'disabled', name='site_status', create_type=False), nullable=False),
    sa.Column('secret_terenkripsi', sa.LargeBinary(), nullable=False),
    sa.Column('connector_version', sa.Text(), nullable=True),
    sa.Column('wp_version', sa.Text(), nullable=True),
    sa.Column('php_version', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('dibuat_pada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('tipe', postgresql.ENUM('scan_site', 'update_package', 'verify_site', name='job_type', create_type=False), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'running', 'success', 'failed', 'unknown', name='job_status', create_type=False), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('hasil', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_class', sa.Text(), nullable=True),
    sa.Column('dibuat_pada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dibuat_oleh', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['dibuat_oleh'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_packages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=False),
    sa.Column('tipe', postgresql.ENUM('core', 'plugin', 'theme', name='package_type', create_type=False), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('nama', sa.Text(), nullable=False),
    sa.Column('versi_terpasang', sa.Text(), nullable=False),
    sa.Column('versi_tersedia', sa.Text(), nullable=True),
    sa.Column('aktif', sa.Boolean(), nullable=False),
    sa.Column('auto_update', sa.Boolean(), nullable=False),
    sa.Column('last_scan_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'tipe', 'slug', name='uq_site_package')
    )
    op.create_index(op.f('ix_site_packages_site_id'), 'site_packages', ['site_id'], unique=False)
    op.create_index(op.f('ix_site_packages_slug'), 'site_packages', ['slug'], unique=False)
    op.create_table('activity_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('site_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Text(), nullable=False),
    sa.Column('pesan', sa.Text(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dibuat_pada', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_log')
    op.drop_index(op.f('ix_site_packages_slug'), table_name='site_packages')
    op.drop_index(op.f('ix_site_packages_site_id'), table_name='site_packages')
    op.drop_table('site_packages')
    op.drop_table('jobs')
    op.drop_table('sites')
    op.drop_table('users')
    op.drop_table('clients')
    # ### end Alembic commands ###
    sa.Enum(name="job_status").drop(op.get_bind())
    sa.Enum(name="job_type").drop(op.get_bind())
    sa.Enum(name="package_type").drop(op.get_bind())
    sa.Enum(name="site_status").drop(op.get_bind())
