import threading
import time

import httpx
import pytest

from wpmgr.models import UptimeHasil, UptimeStatus
from wpmgr.uptime import (
    HasilCek,
    cek_satu,
    cek_semua,
    gangguan_dashboard,
    nilai_kesalahan,
    nilai_respons,
    terapkan,
)


def test_2xx_naik():
    h = nilai_respons(200, {}, "<html>ok</html>", 120)
    assert (h.hasil, h.http_status, h.waktu_ms) == (UptimeHasil.naik, 200, 120)


def test_5xx_gagal_dengan_pesan():
    h = nilai_respons(500, {}, "There has been a critical error on this website.", 80)
    assert h.hasil == UptimeHasil.gagal
    assert h.pesan == "HTTP 500"


def test_503_origin_di_balik_cloudflare_tetap_gagal():
    # Halaman 52x/503 Cloudflare saat origin mati memuat cf-ray DAN kata
    # "cloudflare". Keduanya bukan tanda blokir; menganggapnya blokir
    # menyembunyikan setiap site mati yang memakai Cloudflare.
    body = "<title>example.com | 521: Web server is down</title> ... Cloudflare Ray ID"
    h = nilai_respons(521, {"cf-ray": "8a1b2c3d4e5f-SIN", "server": "cloudflare"}, body, 300)
    assert h.hasil == UptimeHasil.gagal
    h = nilai_respons(503, {"cf-ray": "8a1b-SIN", "server": "cloudflare"}, "Service Unavailable", 300)
    assert h.hasil == UptimeHasil.gagal


@pytest.mark.parametrize(
    ("status", "headers", "body"),
    [
        (403, {"cf-mitigated": "challenge"}, ""),
        (503, {}, "<title>Just a moment...</title><script>window._cf_chl_opt={}</script>"),
        (403, {}, "<title>Attention Required! | Cloudflare</title> Sorry, you have been blocked"),
        (403, {}, "<h1>Your access to this site has been limited by the site owner</h1> Wordfence"),
        (503, {}, "Generated by Wordfence at Tue, 22 Sep 2026"),
        (429, {}, "Too Many Requests"),
    ],
)
def test_halaman_tantangan_dan_blokir_terblokir(status, headers, body):
    assert nilai_respons(status, headers, body, 50).hasil == UptimeHasil.terblokir


def test_403_biasa_gagal():
    assert nilai_respons(403, {}, "Forbidden", 50).hasil == UptimeHasil.gagal


def test_404_gagal():
    assert nilai_respons(404, {}, "Not Found", 50).hasil == UptimeHasil.gagal


def test_kesalahan_timeout():
    h = nilai_kesalahan(httpx.ReadTimeout("x"))
    assert h.hasil == UptimeHasil.gagal
    assert "15 detik" in h.pesan


def test_kesalahan_redirect_berlebihan():
    h = nilai_kesalahan(httpx.TooManyRedirects("x"))
    assert "Redirect" in h.pesan


def test_kesalahan_sertifikat():
    h = nilai_kesalahan(httpx.ConnectError("[SSL: CERTIFICATE_VERIFY_FAILED] certificate has expired"))
    assert h.pesan.startswith("Sertifikat SSL tidak valid")


def test_kesalahan_dns():
    h = nilai_kesalahan(httpx.ConnectError("[Errno -2] Name or service not known"))
    assert "DNS" in h.pesan


def test_kesalahan_koneksi_lain():
    h = nilai_kesalahan(httpx.ConnectError("[Errno 111] Connection refused"))
    assert h.pesan.startswith("Koneksi gagal")


def test_cek_satu_kesalahan_bukan_httperror_dianggap_gagal():
    # httpx.InvalidURL bukan subkelas httpx.HTTPError (mis. dari URL site yang
    # tidak sah tersimpan di DB). Sebelumnya ini lolos dari except dan
    # menghentikan seluruh putaran lewat ThreadPoolExecutor.map.
    def handler(request):
        raise httpx.InvalidURL("URL tidak sah")

    client = httpx.Client(transport=httpx.MockTransport(handler))
    h = cek_satu(client, "https://contoh.test")
    assert h.hasil == UptimeHasil.gagal
    assert h.pesan


class _AliranBesar(httpx.SyncByteStream):
    """Body 10 MB yang dihasilkan sepotong demi sepotong sambil menghitung
    berapa byte yang benar-benar diminta pembaca."""

    def __init__(self, total=10 * 1024 * 1024, potongan=64 * 1024):
        self.total = total
        self.potongan = potongan
        self.terbaca = 0

    def __iter__(self):
        while self.terbaca < self.total:
            self.terbaca += self.potongan
            yield b"a" * self.potongan


def test_cek_satu_hanya_membaca_awal_body_besar():
    aliran = _AliranBesar()

    def handler(request):
        return httpx.Response(200, headers={"content-type": "text/html"}, stream=aliran)

    client = httpx.Client(transport=httpx.MockTransport(handler))
    h = cek_satu(client, "https://contoh.test")
    assert h.hasil == UptimeHasil.naik
    assert h.http_status == 200
    assert aliran.terbaca <= 128 * 1024


def test_cek_satu_tetap_mengenali_halaman_blokir_dari_awal_body():
    body = b"<title>Just a moment...</title>" + b"x" * (5 * 1024 * 1024)

    def handler(request):
        return httpx.Response(503, content=body)

    client = httpx.Client(transport=httpx.MockTransport(handler))
    assert cek_satu(client, "https://contoh.test").hasil == UptimeHasil.terblokir


def test_cek_semua_memutus_cek_yang_melewati_batas(monkeypatch):
    monkeypatch.setattr("wpmgr.uptime.BATAS_PUTARAN", 0.3)
    lepas = threading.Event()

    def cek(url):
        if url == "lambat":
            lepas.wait(10)
        return HasilCek(UptimeHasil.naik, 200, 5)

    mulai = time.monotonic()
    try:
        hasil = cek_semua(["cepat", "lambat", "cepat2"], cek)
    finally:
        lepas.set()
    assert time.monotonic() - mulai < 3
    assert [h.hasil for h in hasil] == [UptimeHasil.naik, UptimeHasil.gagal, UptimeHasil.naik]
    assert hasil[1].pesan == "Tidak selesai dalam batas waktu"


def test_cek_semua_tenggat_per_gelombang_tidak_membatalkan_site_antre(monkeypatch):
    """Dengan 2 thread dan 3 URL yang masing-masing butuh ~0.2 detik, URL ketiga
    baru mulai di gelombang kedua. Tenggat tetap 0.3 detik untuk seluruh
    putaran akan membatalkannya; tenggat per gelombang tidak."""
    monkeypatch.setattr("wpmgr.uptime.BATAS_PUTARAN", 0.3)
    monkeypatch.setattr("wpmgr.uptime.MAKS_PARALEL", 2)

    def cek(url):
        time.sleep(0.2)
        return HasilCek(UptimeHasil.naik, 200, 5)

    hasil = cek_semua(["a", "b", "c"], cek)
    assert [h.hasil for h in hasil] == [UptimeHasil.naik] * 3


@pytest.mark.parametrize(
    ("site", "gagal", "harapan"),
    [(10, 9, True), (10, 8, False), (5, 5, True), (4, 4, False), (0, 0, False)],
)
def test_aturan_gangguan_dashboard(site, gagal, harapan):
    assert gangguan_dashboard(site, gagal) is harapan


def test_satu_kegagalan_belum_mati():
    t = terapkan(UptimeStatus.naik, 0, UptimeHasil.gagal)
    assert (t.status, t.gagal_beruntun, t.buka_insiden) == (UptimeStatus.naik, 1, False)


def test_kegagalan_kedua_mati_dan_membuka_insiden():
    t = terapkan(UptimeStatus.naik, 1, UptimeHasil.gagal)
    assert (t.status, t.gagal_beruntun, t.buka_insiden) == (UptimeStatus.mati, 2, True)


def test_sudah_mati_tidak_membuka_insiden_lagi():
    t = terapkan(UptimeStatus.mati, 2, UptimeHasil.gagal)
    assert (t.status, t.gagal_beruntun, t.buka_insiden) == (UptimeStatus.mati, 3, False)


def test_naik_mengembalikan_penghitung_dan_menutup():
    t = terapkan(UptimeStatus.mati, 5, UptimeHasil.naik)
    assert (t.status, t.gagal_beruntun, t.tutup_insiden) == (UptimeStatus.naik, 0, True)


def test_terblokir_tidak_mengubah_penghitung_dan_tanpa_insiden():
    t = terapkan(UptimeStatus.naik, 1, UptimeHasil.terblokir)
    assert (t.status, t.gagal_beruntun, t.buka_insiden, t.tutup_insiden) == (
        UptimeStatus.terblokir, 1, False, False)


def test_site_baru_gagal_sekali_tetap_belum_dicek():
    t = terapkan(UptimeStatus.belum_dicek, 0, UptimeHasil.gagal)
    assert t.status == UptimeStatus.belum_dicek
