"""Uptime: menilai satu cek, menentukan transisi status, dan menjalankan putaran.

Bagian penilaian murni (tanpa jaringan dan database) supaya aturan yang
menentukan kapan sebuah site dinyatakan mati bisa diuji langsung.
"""

import logging
import math
import time
import uuid
from collections.abc import Callable, Sequence
from concurrent.futures import ThreadPoolExecutor, wait
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone

import httpx
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from wpmgr.models import (
    Site,
    SiteStatus,
    UptimeCheck,
    UptimeHasil,
    UptimeInsiden,
    UptimePutaran,
    UptimeStatus,
)

log = logging.getLogger("wpmgr.uptime")

GAGAL_UNTUK_MATI = 2
MIN_SITE_ATURAN_GANGGUAN = 5
AMBANG_GANGGUAN = 0.8

# Hanya penanda halaman tantangan/blokir. Header cf-ray dan kata "cloudflare"
# sengaja TIDAK dipakai: Cloudflare membubuhkannya ke setiap respons yang ia
# proksikan, termasuk halaman 52x ketika origin benar-benar mati (R15 Lapis 1).
_PENANDA_BLOKIR = (
    "_cf_chl_opt",
    "challenge-platform",
    "<title>just a moment...</title>",
    "attention required! | cloudflare",
    "sorry, you have been blocked",
    "your access to this site has been limited",
    "generated by wordfence",
)


@dataclass(frozen=True)
class HasilCek:
    hasil: UptimeHasil
    http_status: int | None = None
    waktu_ms: int | None = None
    pesan: str | None = None


@dataclass(frozen=True)
class Transisi:
    status: UptimeStatus
    gagal_beruntun: int
    buka_insiden: bool
    tutup_insiden: bool


def _halaman_blokir(headers: dict[str, str], body: str) -> bool:
    rendah = {k.lower(): (v or "").lower() for k, v in headers.items()}
    if rendah.get("cf-mitigated") == "challenge":
        return True
    cuplikan = body[:5000].lower()
    return any(p in cuplikan for p in _PENANDA_BLOKIR)


def nilai_respons(status: int, headers: dict[str, str], body: str, waktu_ms: int) -> HasilCek:
    if 200 <= status < 300:
        return HasilCek(UptimeHasil.naik, status, waktu_ms)
    # 429 berarti server menjawab dan sedang membatasi dashboard: site hidup.
    if status == 429 or (status in (403, 503) and _halaman_blokir(headers, body)):
        return HasilCek(UptimeHasil.terblokir, status, waktu_ms,
                        "Permintaan dashboard diblokir firewall site")
    return HasilCek(UptimeHasil.gagal, status, waktu_ms, f"HTTP {status}")


def nilai_kesalahan(exc: Exception) -> HasilCek:
    teks = str(exc)
    if isinstance(exc, httpx.TooManyRedirects):
        pesan = "Redirect lebih dari 5 kali"
    elif isinstance(exc, httpx.TimeoutException):
        pesan = "Tidak menjawab dalam 15 detik"
    elif isinstance(exc, httpx.ConnectError):
        rendah = teks.lower()
        if "certificate" in rendah or "ssl" in rendah:
            pesan = f"Sertifikat SSL tidak valid: {teks[:200]}"
        elif any(p in rendah for p in ("name or service not known", "getaddrinfo",
                                        "nodename nor servname", "no address associated")):
            pesan = "Nama domain tidak dapat di-resolve (DNS)"
        else:
            pesan = f"Koneksi gagal: {teks[:200]}"
    else:
        pesan = f"{type(exc).__name__}: {teks[:200]}"
    return HasilCek(UptimeHasil.gagal, None, None, pesan)


def gangguan_dashboard(jumlah_site: int, jumlah_gagal: int) -> bool:
    """Bila hampir semua site gagal bersamaan, yang bermasalah jaringan dashboard."""
    return (
        jumlah_site >= MIN_SITE_ATURAN_GANGGUAN
        and jumlah_gagal / jumlah_site > AMBANG_GANGGUAN
    )


def terapkan(status_lama: UptimeStatus, gagal_beruntun: int, hasil: UptimeHasil) -> Transisi:
    if hasil == UptimeHasil.naik:
        # tutup_insiden selalu True: lapisan database menutup insiden hanya
        # bila memang ada yang terbuka, termasuk insiden yang dibuka sebelum
        # site sempat berstatus terblokir.
        return Transisi(UptimeStatus.naik, 0, False, True)
    if hasil == UptimeHasil.terblokir:
        return Transisi(UptimeStatus.terblokir, gagal_beruntun, False, False)
    baru = gagal_beruntun + 1
    if baru >= GAGAL_UNTUK_MATI:
        return Transisi(UptimeStatus.mati, baru, status_lama != UptimeStatus.mati, False)
    return Transisi(status_lama, baru, False, False)


UA = "WPManager-Uptime/2.0"
TIMEOUT = 15.0
MAKS_REDIRECT = 5
MAKS_PARALEL = 10
# Penanda blokir hanya dicari di 5000 karakter pertama (_halaman_blokir), jadi
# body tidak perlu dibaca lebih dari itu. Tanpa batas, site yang mengirim body
# raksasa atau menetes pelan menahan satu thread putaran jauh melewati TIMEOUT
# (timeout httpx berlaku per operasi baca, bukan untuk seluruh body).
MAKS_BODY = 5000
# Batas keras satu putaran: satu cek bisa menghabiskan TIMEOUT untuk koneksi
# ditambah hampir TIMEOUT untuk satu potongan baca terakhir sebelum tenggat
# di cek_satu() diperiksa. Cek yang belum selesai sesudahnya dianggap gagal.
BATAS_PUTARAN = TIMEOUT * 2 + 5


def buat_klien_http(transport: httpx.BaseTransport | None = None) -> httpx.Client:
    return httpx.Client(
        follow_redirects=True, max_redirects=MAKS_REDIRECT, timeout=TIMEOUT,
        headers={"User-Agent": UA}, transport=transport,
    )


def _decode_cuplikan(data: bytes, charset: str | None) -> str:
    try:
        return data.decode(charset or "utf-8", errors="replace")
    except LookupError:
        return data.decode("utf-8", errors="replace")


def cek_satu(client: httpx.Client, url: str) -> HasilCek:
    mulai = time.monotonic()
    try:
        with client.stream("GET", url) as r:
            cuplikan = bytearray()
            for potongan in r.iter_bytes():
                cuplikan += potongan
                if len(cuplikan) >= MAKS_BODY or time.monotonic() - mulai > TIMEOUT:
                    break
            status, headers = r.status_code, dict(r.headers)
            body = _decode_cuplikan(bytes(cuplikan[:MAKS_BODY]), r.charset_encoding)
    except httpx.HTTPError as exc:
        return nilai_kesalahan(exc)
    except Exception as exc:
        # mis. httpx.InvalidURL dari URL site yang tidak sah tersimpan di DB:
        # bukan subkelas HTTPError, jadi tanpa ini lolos dari except dan
        # menghentikan seluruh putaran lewat Future.result() di cek_semua
        # (satu site rusak wajib gagal sendiri, bukan menggagalkan semua site).
        log.exception("Kesalahan tak terduga saat mengecek uptime %s", url)
        return nilai_kesalahan(exc)
    return nilai_respons(status, headers, body, int((time.monotonic() - mulai) * 1000))


def cek_semua(urls: Sequence[str], cek_fn: Callable[[str], HasilCek]) -> list[HasilCek]:
    """Cek semua URL paralel dengan batas waktu keras; urutan hasil = urutan URL.

    Tidak memakai `with ThreadPoolExecutor(...)`: keluarnya menunggu SEMUA
    thread selesai, sehingga satu cek yang macet menahan putaran (dan kunci
    advisory uptime) tanpa batas. Thread yang macet dibiarkan selesai sendiri
    di latar belakang; hasilnya tidak dipakai.
    """
    ex = ThreadPoolExecutor(max_workers=MAKS_PARALEL)
    # BATAS_PUTARAN per gelombang: dengan MAKS_PARALEL thread, URL ke-11 dst.
    # baru mulai setelah thread sebelumnya bebas. Tenggat tetap untuk seluruh
    # putaran akan membatalkan site yang masih antre (lalu tercatat gagal dan
    # bisa memicu aturan gangguan_dashboard) begitu lebih dari ~20 site lambat.
    gelombang = max(1, math.ceil(len(urls) / MAKS_PARALEL))
    try:
        futs = [ex.submit(cek_fn, u) for u in urls]
        wait(futs, timeout=BATAS_PUTARAN * gelombang)
        return [
            f.result() if f.done() and not f.cancelled()
            else HasilCek(UptimeHasil.gagal, pesan="Tidak selesai dalam batas waktu")
            for f in futs
        ]
    finally:
        ex.shutdown(wait=False, cancel_futures=True)


def _awal_deret_gagal(sesi: Session, site_id, sekarang: datetime) -> datetime:
    """Waktu kegagalan pertama dalam deret yang baru mencapai ambang."""
    waktu = sesi.scalars(
        select(UptimeCheck.dicek_pada)
        .join(UptimePutaran, UptimePutaran.id == UptimeCheck.putaran_id)
        .where(
            UptimeCheck.site_id == site_id,
            UptimeCheck.hasil == UptimeHasil.gagal,
            UptimeCheck.dicek_pada < sekarang,
            UptimePutaran.gangguan_dashboard.is_(False),
        )
        .order_by(UptimeCheck.dicek_pada.desc())
        .limit(GAGAL_UNTUK_MATI - 1)
    ).all()
    return waktu[-1] if waktu else sekarang


def _terapkan_ke_site(sesi: Session, site: Site, h: HasilCek, sekarang: datetime) -> None:
    t = terapkan(site.uptime_status, site.uptime_gagal_beruntun, h.hasil)
    terbuka = sesi.scalar(
        select(UptimeInsiden).where(
            UptimeInsiden.site_id == site.id, UptimeInsiden.selesai.is_(None)
        )
    )
    sejak = sekarang
    if t.buka_insiden and terbuka is None:
        sejak = _awal_deret_gagal(sesi, site.id, sekarang)
        sesi.add(UptimeInsiden(
            site_id=site.id, mulai=sejak,
            penyebab=h.pesan or f"HTTP {h.http_status}", http_status=h.http_status,
        ))
    if t.tutup_insiden and terbuka is not None:
        terbuka.selesai = sekarang
    if t.status != site.uptime_status:
        site.uptime_sejak = sejak
    site.uptime_status = t.status
    site.uptime_gagal_beruntun = t.gagal_beruntun


def jalankan_putaran(
    sesi: Session, cek_fn: Callable[[str], HasilCek], sekarang: datetime | None = None
) -> UptimePutaran | None:
    sites = sesi.scalars(
        select(Site).where(Site.status != SiteStatus.disabled).order_by(Site.nama)
    ).all()
    if not sites:
        return None

    hasil = cek_semua([s.url for s in sites], cek_fn)

    sekarang = sekarang or datetime.now(timezone.utc)
    jumlah_gagal = sum(1 for h in hasil if h.hasil == UptimeHasil.gagal)
    gangguan = gangguan_dashboard(len(sites), jumlah_gagal)
    putaran = UptimePutaran(mulai=sekarang, jumlah_site=len(sites),
                            jumlah_gagal=jumlah_gagal, gangguan_dashboard=gangguan)
    sesi.add(putaran)
    sesi.flush()

    for site, h in zip(sites, hasil):
        sesi.add(UptimeCheck(
            putaran_id=putaran.id, site_id=site.id, dicek_pada=sekarang, hasil=h.hasil,
            http_status=h.http_status, waktu_ms=h.waktu_ms, pesan=h.pesan,
        ))
        if not gangguan:
            _terapkan_ke_site(sesi, site, h, sekarang)
    sesi.commit()
    return putaran


def persen_uptime_per_site(
    sesi: Session, sejak: datetime, site_ids: Sequence[uuid.UUID] | None = None
) -> dict[uuid.UUID, float | None]:
    """Persen cek `naik` per site, tanpa putaran gangguan dashboard dan tanpa hasil terblokir.

    `site_ids` membatasi query ke site yang memang akan ditampilkan (mis. halaman
    Kesehatan). Tanpa itu, satu-satunya indeks (`site_id, dicek_pada`) tidak membantu
    kalau hanya `dicek_pada` yang difilter -- setiap penyegaran (tiap 60 detik per tab
    yang terbuka) akan seq-scan seluruh riwayat `uptime_checks`. `None` berarti tanpa
    filter site (perilaku lama, untuk pemanggil lain kalau ada); daftar kosong berarti
    tidak ada site yang perlu dicari sama sekali, jadi query dilewati.
    """
    if site_ids is not None and not site_ids:
        return {}
    naik = func.count().filter(UptimeCheck.hasil == UptimeHasil.naik)
    gagal = func.count().filter(UptimeCheck.hasil == UptimeHasil.gagal)
    kondisi = [UptimeCheck.dicek_pada >= sejak, UptimePutaran.gangguan_dashboard.is_(False)]
    if site_ids is not None:
        kondisi.append(UptimeCheck.site_id.in_(site_ids))
    baris = sesi.execute(
        select(UptimeCheck.site_id, naik, gagal)
        .join(UptimePutaran, UptimePutaran.id == UptimeCheck.putaran_id)
        .where(*kondisi)
        .group_by(UptimeCheck.site_id)
    ).all()
    return {
        site_id: (round(n / (n + g) * 100, 2) if n + g else None)
        for site_id, n, g in baris
    }


def persen_uptime(sesi: Session, site_id, sejak: datetime) -> float | None:
    # site_ids=[site_id], bukan tanpa filter: lihat catatan performa di
    # persen_uptime_per_site -- tanpa itu setiap tab Uptime yang dibuka
    # seq-scan seluruh riwayat uptime_checks, bukan cuma milik site ini.
    return persen_uptime_per_site(sesi, sejak, [site_id]).get(site_id)


def uptime_harian(sesi: Session, site_id, sekarang: datetime, hari: int) -> list[dict]:
    awal = (sekarang - timedelta(days=hari - 1)).replace(hour=0, minute=0, second=0, microsecond=0)
    # func.timezone("UTC", ...) dulu, baru date_trunc: date_trunc('day', timestamptz)
    # membagi hari menurut TimeZone SESI Postgres, bukan UTC. Mesin koneksi sudah
    # dipatok ke UTC (wpmgr/db.py), tapi fungsi ini tidak boleh diam-diam salah
    # kalau suatu saat dipanggil lewat sesi/koneksi lain yang tidak dipatok --
    # timezone("UTC", kolom) mengubahnya jadi timestamp tanpa zona dalam waktu
    # UTC dulu, sehingga date_trunc sesudahnya murni operasi kalender, tak
    # tersentuh TimeZone sesi sama sekali.
    kolom_hari = func.date_trunc("day", func.timezone("UTC", UptimeCheck.dicek_pada)).label("hari")
    naik = func.count().filter(UptimeCheck.hasil == UptimeHasil.naik)
    gagal = func.count().filter(UptimeCheck.hasil == UptimeHasil.gagal)
    peta = {
        baris.hari.date(): (baris[1], baris[2])
        for baris in sesi.execute(
            select(kolom_hari, naik, gagal)
            .join(UptimePutaran, UptimePutaran.id == UptimeCheck.putaran_id)
            .where(UptimeCheck.site_id == site_id, UptimeCheck.dicek_pada >= awal,
                   UptimePutaran.gangguan_dashboard.is_(False))
            .group_by(kolom_hari)
        ).all()
    }
    hasil = []
    for i in range(hari):
        tanggal = awal.date() + timedelta(days=i)
        n, g = peta.get(tanggal, (0, 0))
        hasil.append({"tanggal": tanggal.isoformat(),
                      "persen": round(n / (n + g) * 100, 2) if n + g else None})
    return hasil


def rata_waktu_ms(sesi: Session, site_id, sejak: datetime) -> int | None:
    # Sama seperti persen_uptime_per_site: putaran gangguan_dashboard tidak
    # merepresentasikan site ini sungguhan lambat/cepat, cuma jaringan
    # dashboard yang bermasalah -- tanpa filter ini waktu respons semua site
    # ikut tercemar oleh satu putaran yang gagal massal.
    nilai = sesi.scalar(
        select(func.avg(UptimeCheck.waktu_ms))
        .join(UptimePutaran, UptimePutaran.id == UptimeCheck.putaran_id)
        .where(
            UptimeCheck.site_id == site_id, UptimeCheck.hasil == UptimeHasil.naik,
            UptimeCheck.dicek_pada >= sejak, UptimePutaran.gangguan_dashboard.is_(False),
        )
    )
    return int(nilai) if nilai is not None else None


def teks_durasi(detik: float) -> str:
    menit = int(detik // 60)
    jam, menit = divmod(menit, 60)
    hari, jam = divmod(jam, 24)
    bagian = []
    if hari:
        bagian.append(f"{hari} hari")
    if jam:
        bagian.append(f"{jam} jam")
    if menit or not bagian:
        bagian.append(f"{menit} menit")
    return " ".join(bagian)
