"""Uptime: menilai satu cek, menentukan transisi status, dan menjalankan putaran.

Bagian penilaian murni (tanpa jaringan dan database) supaya aturan yang
menentukan kapan sebuah site dinyatakan mati bisa diuji langsung.
"""

import logging
import time
from collections.abc import Callable
from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass
from datetime import datetime, timezone

import httpx
from sqlalchemy import select
from sqlalchemy.orm import Session

from wpmgr.models import (
    Site,
    SiteStatus,
    UptimeCheck,
    UptimeHasil,
    UptimeInsiden,
    UptimePutaran,
    UptimeStatus,
)

log = logging.getLogger("wpmgr.uptime")

GAGAL_UNTUK_MATI = 2
MIN_SITE_ATURAN_GANGGUAN = 5
AMBANG_GANGGUAN = 0.8

# Hanya penanda halaman tantangan/blokir. Header cf-ray dan kata "cloudflare"
# sengaja TIDAK dipakai: Cloudflare membubuhkannya ke setiap respons yang ia
# proksikan, termasuk halaman 52x ketika origin benar-benar mati (R15 Lapis 1).
_PENANDA_BLOKIR = (
    "_cf_chl_opt",
    "challenge-platform",
    "<title>just a moment...</title>",
    "attention required! | cloudflare",
    "sorry, you have been blocked",
    "your access to this site has been limited",
    "generated by wordfence",
)


@dataclass(frozen=True)
class HasilCek:
    hasil: UptimeHasil
    http_status: int | None = None
    waktu_ms: int | None = None
    pesan: str | None = None


@dataclass(frozen=True)
class Transisi:
    status: UptimeStatus
    gagal_beruntun: int
    buka_insiden: bool
    tutup_insiden: bool


def _halaman_blokir(headers: dict[str, str], body: str) -> bool:
    rendah = {k.lower(): (v or "").lower() for k, v in headers.items()}
    if rendah.get("cf-mitigated") == "challenge":
        return True
    cuplikan = body[:5000].lower()
    return any(p in cuplikan for p in _PENANDA_BLOKIR)


def nilai_respons(status: int, headers: dict[str, str], body: str, waktu_ms: int) -> HasilCek:
    if 200 <= status < 300:
        return HasilCek(UptimeHasil.naik, status, waktu_ms)
    # 429 berarti server menjawab dan sedang membatasi dashboard: site hidup.
    if status == 429 or (status in (403, 503) and _halaman_blokir(headers, body)):
        return HasilCek(UptimeHasil.terblokir, status, waktu_ms,
                        "Permintaan dashboard diblokir firewall site")
    return HasilCek(UptimeHasil.gagal, status, waktu_ms, f"HTTP {status}")


def nilai_kesalahan(exc: Exception) -> HasilCek:
    teks = str(exc)
    if isinstance(exc, httpx.TooManyRedirects):
        pesan = "Redirect lebih dari 5 kali"
    elif isinstance(exc, httpx.TimeoutException):
        pesan = "Tidak menjawab dalam 15 detik"
    elif isinstance(exc, httpx.ConnectError):
        rendah = teks.lower()
        if "certificate" in rendah or "ssl" in rendah:
            pesan = f"Sertifikat SSL tidak valid: {teks[:200]}"
        elif any(p in rendah for p in ("name or service not known", "getaddrinfo",
                                        "nodename nor servname", "no address associated")):
            pesan = "Nama domain tidak dapat di-resolve (DNS)"
        else:
            pesan = f"Koneksi gagal: {teks[:200]}"
    else:
        pesan = f"{type(exc).__name__}: {teks[:200]}"
    return HasilCek(UptimeHasil.gagal, None, None, pesan)


def gangguan_dashboard(jumlah_site: int, jumlah_gagal: int) -> bool:
    """Bila hampir semua site gagal bersamaan, yang bermasalah jaringan dashboard."""
    return (
        jumlah_site >= MIN_SITE_ATURAN_GANGGUAN
        and jumlah_gagal / jumlah_site > AMBANG_GANGGUAN
    )


def terapkan(status_lama: UptimeStatus, gagal_beruntun: int, hasil: UptimeHasil) -> Transisi:
    if hasil == UptimeHasil.naik:
        # tutup_insiden selalu True: lapisan database menutup insiden hanya
        # bila memang ada yang terbuka, termasuk insiden yang dibuka sebelum
        # site sempat berstatus terblokir.
        return Transisi(UptimeStatus.naik, 0, False, True)
    if hasil == UptimeHasil.terblokir:
        return Transisi(UptimeStatus.terblokir, gagal_beruntun, False, False)
    baru = gagal_beruntun + 1
    if baru >= GAGAL_UNTUK_MATI:
        return Transisi(UptimeStatus.mati, baru, status_lama != UptimeStatus.mati, False)
    return Transisi(status_lama, baru, False, False)


UA = "WPManager-Uptime/2.0"
TIMEOUT = 15.0
MAKS_REDIRECT = 5
MAKS_PARALEL = 10


def buat_klien_http(transport: httpx.BaseTransport | None = None) -> httpx.Client:
    return httpx.Client(
        follow_redirects=True, max_redirects=MAKS_REDIRECT, timeout=TIMEOUT,
        headers={"User-Agent": UA}, transport=transport,
    )


def cek_satu(client: httpx.Client, url: str) -> HasilCek:
    mulai = time.monotonic()
    try:
        r = client.get(url)
    except httpx.HTTPError as exc:
        return nilai_kesalahan(exc)
    except Exception as exc:
        # mis. httpx.InvalidURL dari URL site yang tidak sah tersimpan di DB:
        # bukan subkelas HTTPError, jadi tanpa ini lolos dari except dan
        # menghentikan seluruh putaran lewat ThreadPoolExecutor.map (satu
        # site rusak wajib gagal sendiri, bukan menggagalkan semua site).
        log.exception("Kesalahan tak terduga saat mengecek uptime %s", url)
        return nilai_kesalahan(exc)
    return nilai_respons(r.status_code, dict(r.headers), r.text,
                         int((time.monotonic() - mulai) * 1000))


def _awal_deret_gagal(sesi: Session, site_id, sekarang: datetime) -> datetime:
    """Waktu kegagalan pertama dalam deret yang baru mencapai ambang."""
    waktu = sesi.scalars(
        select(UptimeCheck.dicek_pada)
        .join(UptimePutaran, UptimePutaran.id == UptimeCheck.putaran_id)
        .where(
            UptimeCheck.site_id == site_id,
            UptimeCheck.hasil == UptimeHasil.gagal,
            UptimeCheck.dicek_pada < sekarang,
            UptimePutaran.gangguan_dashboard.is_(False),
        )
        .order_by(UptimeCheck.dicek_pada.desc())
        .limit(GAGAL_UNTUK_MATI - 1)
    ).all()
    return waktu[-1] if waktu else sekarang


def _terapkan_ke_site(sesi: Session, site: Site, h: HasilCek, sekarang: datetime) -> None:
    t = terapkan(site.uptime_status, site.uptime_gagal_beruntun, h.hasil)
    terbuka = sesi.scalar(
        select(UptimeInsiden).where(
            UptimeInsiden.site_id == site.id, UptimeInsiden.selesai.is_(None)
        )
    )
    sejak = sekarang
    if t.buka_insiden and terbuka is None:
        sejak = _awal_deret_gagal(sesi, site.id, sekarang)
        sesi.add(UptimeInsiden(
            site_id=site.id, mulai=sejak,
            penyebab=h.pesan or f"HTTP {h.http_status}", http_status=h.http_status,
        ))
    if t.tutup_insiden and terbuka is not None:
        terbuka.selesai = sekarang
    if t.status != site.uptime_status:
        site.uptime_sejak = sejak
    site.uptime_status = t.status
    site.uptime_gagal_beruntun = t.gagal_beruntun


def jalankan_putaran(
    sesi: Session, cek_fn: Callable[[str], HasilCek], sekarang: datetime | None = None
) -> UptimePutaran | None:
    sites = sesi.scalars(
        select(Site).where(Site.status != SiteStatus.disabled).order_by(Site.nama)
    ).all()
    if not sites:
        return None

    with ThreadPoolExecutor(max_workers=MAKS_PARALEL) as ex:
        hasil = list(ex.map(cek_fn, [s.url for s in sites]))

    sekarang = sekarang or datetime.now(timezone.utc)
    jumlah_gagal = sum(1 for h in hasil if h.hasil == UptimeHasil.gagal)
    gangguan = gangguan_dashboard(len(sites), jumlah_gagal)
    putaran = UptimePutaran(mulai=sekarang, jumlah_site=len(sites),
                            jumlah_gagal=jumlah_gagal, gangguan_dashboard=gangguan)
    sesi.add(putaran)
    sesi.flush()

    for site, h in zip(sites, hasil):
        sesi.add(UptimeCheck(
            putaran_id=putaran.id, site_id=site.id, dicek_pada=sekarang, hasil=h.hasil,
            http_status=h.http_status, waktu_ms=h.waktu_ms, pesan=h.pesan,
        ))
        if not gangguan:
            _terapkan_ke_site(sesi, site, h, sekarang)
    sesi.commit()
    return putaran
