"""Uptime: menilai satu cek, menentukan transisi status, dan menjalankan putaran.

Bagian penilaian murni (tanpa jaringan dan database) supaya aturan yang
menentukan kapan sebuah site dinyatakan mati bisa diuji langsung.
"""

from dataclasses import dataclass

import httpx

from wpmgr.models import UptimeHasil, UptimeStatus

GAGAL_UNTUK_MATI = 2
MIN_SITE_ATURAN_GANGGUAN = 5
AMBANG_GANGGUAN = 0.8

# Hanya penanda halaman tantangan/blokir. Header cf-ray dan kata "cloudflare"
# sengaja TIDAK dipakai: Cloudflare membubuhkannya ke setiap respons yang ia
# proksikan, termasuk halaman 52x ketika origin benar-benar mati (R15 Lapis 1).
_PENANDA_BLOKIR = (
    "_cf_chl_opt",
    "challenge-platform",
    "<title>just a moment...</title>",
    "attention required! | cloudflare",
    "sorry, you have been blocked",
    "your access to this site has been limited",
    "generated by wordfence",
)


@dataclass(frozen=True)
class HasilCek:
    hasil: UptimeHasil
    http_status: int | None = None
    waktu_ms: int | None = None
    pesan: str | None = None


@dataclass(frozen=True)
class Transisi:
    status: UptimeStatus
    gagal_beruntun: int
    buka_insiden: bool
    tutup_insiden: bool


def _halaman_blokir(headers: dict[str, str], body: str) -> bool:
    rendah = {k.lower(): (v or "").lower() for k, v in headers.items()}
    if rendah.get("cf-mitigated") == "challenge":
        return True
    cuplikan = body[:5000].lower()
    return any(p in cuplikan for p in _PENANDA_BLOKIR)


def nilai_respons(status: int, headers: dict[str, str], body: str, waktu_ms: int) -> HasilCek:
    if 200 <= status < 300:
        return HasilCek(UptimeHasil.naik, status, waktu_ms)
    # 429 berarti server menjawab dan sedang membatasi dashboard: site hidup.
    if status == 429 or (status in (403, 503) and _halaman_blokir(headers, body)):
        return HasilCek(UptimeHasil.terblokir, status, waktu_ms,
                        "Permintaan dashboard diblokir firewall site")
    return HasilCek(UptimeHasil.gagal, status, waktu_ms, f"HTTP {status}")


def nilai_kesalahan(exc: Exception) -> HasilCek:
    teks = str(exc)
    if isinstance(exc, httpx.TooManyRedirects):
        pesan = "Redirect lebih dari 5 kali"
    elif isinstance(exc, httpx.TimeoutException):
        pesan = "Tidak menjawab dalam 15 detik"
    elif isinstance(exc, httpx.ConnectError):
        rendah = teks.lower()
        if "certificate" in rendah or "ssl" in rendah:
            pesan = f"Sertifikat SSL tidak valid: {teks[:200]}"
        elif any(p in rendah for p in ("name or service not known", "getaddrinfo",
                                        "nodename nor servname", "no address associated")):
            pesan = "Nama domain tidak dapat di-resolve (DNS)"
        else:
            pesan = f"Koneksi gagal: {teks[:200]}"
    else:
        pesan = f"{type(exc).__name__}: {teks[:200]}"
    return HasilCek(UptimeHasil.gagal, None, None, pesan)


def gangguan_dashboard(jumlah_site: int, jumlah_gagal: int) -> bool:
    """Bila hampir semua site gagal bersamaan, yang bermasalah jaringan dashboard."""
    return (
        jumlah_site >= MIN_SITE_ATURAN_GANGGUAN
        and jumlah_gagal / jumlah_site > AMBANG_GANGGUAN
    )


def terapkan(status_lama: UptimeStatus, gagal_beruntun: int, hasil: UptimeHasil) -> Transisi:
    if hasil == UptimeHasil.naik:
        # tutup_insiden selalu True: lapisan database menutup insiden hanya
        # bila memang ada yang terbuka, termasuk insiden yang dibuka sebelum
        # site sempat berstatus terblokir.
        return Transisi(UptimeStatus.naik, 0, False, True)
    if hasil == UptimeHasil.terblokir:
        return Transisi(UptimeStatus.terblokir, gagal_beruntun, False, False)
    baru = gagal_beruntun + 1
    if baru >= GAGAL_UNTUK_MATI:
        return Transisi(UptimeStatus.mati, baru, status_lama != UptimeStatus.mati, False)
    return Transisi(status_lama, baru, False, False)
